### PR TITLE
Create Lecture2Detailed.md

### PR DESCRIPTION
**Pull request by rikgirbes**
Detailed Lecture 2 Overview

### CODE REVIEW

**Comment by rikgirbes** [comment]
The summary should probably also be updated @nstankov-bg ?

**Comment by nstankov-bg** [comment]
Yes please, @rikgirbes  Update the summary as well.

**Comment by rikgirbes** [comment]
Done. Merge?

**Comment by nstankov-bg** [comment]
Thank you!

**Review by nstankov-bg — APPROVED** [review]
Thanks!

**Pull request merged**
